# Generated by Django 5.0.5 on 2024-05-06 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sos_rs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='founded_date',
            new_name='missing_date',
        ),
    ]
