# Generated by Django 5.0.5 on 2024-05-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos_rs_app', '0002_rename_founded_date_user_missing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='missing_date',
            field=models.DateField(),
        ),
    ]
